name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js (17.0.0)
        uses: actions/setup-node@v1
        with:
          node-version: '17.0.0'

      - name: Install Pacakges
        run: npm ci

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}